### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by Polygonalr** [AY2223S1-CS2103T-T13-2/tp#46]
### User Story

As a financial advisor, I want to be reminded of client meetings so that I will not miss them.

### Tasks

- [x] Add new `Reminder` attribute class for `Person`
- [x] Modify the UI to show all `Reminder` for a `Person` with `show` command
- [x] Show reminders that are due soon on every launch
