### ISSUE TITLE
UI: Layout changes

### ISSUE THREAD

**Issue by Polygonalr** [AY2223S1-CS2103T-T13-2/tp#57]
## Objective

Change the UI layout and create new components to allow for integration with new features such as Reminders and Command History (if we have time~)

## Tasks
- [x] Layout changes to make more space for the `show` command
- [x] Create new UI components for Reminder feature
- [x] Create new component/scene which will be shown on every launch (to display welcome messages and reminders for the day)
